import { Dataset, PricingTier } from './types'

export const datasets: Dataset[] = [
  {
    id: '1',
    title: 'Code Review Conversations',
    description: 'High-quality code review discussions from GitHub and Stack Overflow with human preferences labeled.',
    domain: 'coding',
    source: 'stackoverflow',
    size: '2.3 GB',
    qualityScore: 94,
    price: 299,
    downloadCount: 1234,
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    title: 'Scientific Paper Summaries',
    description: 'Academic paper abstracts and human-written summaries from arXiv with preference rankings.',
    domain: 'technical',
    source: 'arxiv',
    size: '5.1 GB',
    qualityScore: 97,
    price: 499,
    downloadCount: 892,
    createdAt: '2024-02-20',
  },
  {
    id: '3',
    title: 'Policy Discussion Threads',
    description: 'Government policy discussions with human feedback on response quality and helpfulness.',
    domain: 'government',
    source: 'reddit',
    size: '1.8 GB',
    qualityScore: 89,
    price: 199,
    downloadCount: 567,
    createdAt: '2024-01-28',
  },
  {
    id: '4',
    title: 'Technical Documentation QA',
    description: 'Question-answer pairs from technical documentation with expert annotations.',
    domain: 'technical',
    source: 'stackoverflow',
    size: '3.7 GB',
    qualityScore: 92,
    price: 349,
    downloadCount: 1089,
    createdAt: '2024-03-05',
  },
  {
    id: '5',
    title: 'Algorithm Explanations',
    description: 'Step-by-step algorithm explanations ranked by clarity and correctness.',
    domain: 'coding',
    source: 'reddit',
    size: '1.2 GB',
    qualityScore: 88,
    price: 149,
    downloadCount: 756,
    createdAt: '2024-02-14',
  },
  {
    id: '6',
    title: 'Research Methodology Discussions',
    description: 'Academic methodology debates with preference labels for argument quality.',
    domain: 'technical',
    source: 'arxiv',
    size: '4.5 GB',
    qualityScore: 95,
    price: 449,
    downloadCount: 423,
    createdAt: '2024-03-12',
  },
  {
    id: '7',
    title: 'Legal Document Analysis',
    description: 'Government legal documents with human-annotated explanations and summaries.',
    domain: 'government',
    source: 'reddit',
    size: '2.9 GB',
    qualityScore: 91,
    price: 399,
    downloadCount: 334,
    createdAt: '2024-01-30',
  },
  {
    id: '8',
    title: 'Debug Conversation Pairs',
    description: 'Real debugging sessions with human preferences for helpful vs unhelpful responses.',
    domain: 'coding',
    source: 'stackoverflow',
    size: '6.2 GB',
    qualityScore: 96,
    price: 599,
    downloadCount: 1567,
    createdAt: '2024-02-28',
  },
  {
    id: '9',
    title: 'Public Policy Summaries',
    description: 'Government policy summaries with readability and accuracy rankings.',
    domain: 'government',
    source: 'arxiv',
    size: '2.1 GB',
    qualityScore: 87,
    price: 249,
    downloadCount: 289,
    createdAt: '2024-03-08',
  },
]

export const pricingTiers: PricingTier[] = [
  {
    name: 'Free',
    price: 0,
    description: 'Perfect for exploring and small experiments',
    features: [
      '5 dataset downloads per month',
      'Basic quality metrics',
      'Community support',
      'API access (100 calls/day)',
      'Sample datasets only',
    ],
    cta: 'Get Started',
  },
  {
    name: 'Pro',
    price: 99,
    description: 'For serious AI researchers and small teams',
    features: [
      '50 dataset downloads per month',
      'Advanced quality analytics',
      'Priority email support',
      'API access (10,000 calls/day)',
      'Full dataset access',
      'Custom filtering options',
      'Export to multiple formats',
    ],
    highlighted: true,
    cta: 'Start Pro Trial',
  },
  {
    name: 'Enterprise',
    price: 499,
    description: 'For organizations with advanced needs',
    features: [
      'Unlimited dataset downloads',
      'Premium quality assurance',
      '24/7 dedicated support',
      'Unlimited API access',
      'Custom dataset creation',
      'White-label options',
      'SLA guarantees',
      'On-premise deployment',
    ],
    cta: 'Contact Sales',
  },
]
